BookStore/Areas/Admin/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BookController : Controller
    {
        private ApplicationDbContext _db;
        private IHostingEnvironment _he;

        public BookController(ApplicationDbContext db, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
        }
        public IActionResult Index()
        {
            return View(_db.Books.Include(c=>c.ProductTypes).Include(f=>f.SpecialTagName).ToList());
        }
        //POST Index Action Method
        [HttpPost]
        public IActionResult Index(decimal? lowAmount, decimal? largeAmount)
        {
            var books = _db.Books.Include(c => c.ProductTypes).Include(c => c.SpecialTagName)
                .Where(c => c.Price >= lowAmount && c.Price <= largeAmount).ToList();
            if(lowAmount==null || largeAmount == null)
            {
                 books = _db.Books.Include(c => c.ProductTypes).Include(c => c.SpecialTagName).ToList();

            }
            return View(books);
        }

        //Get Create Method
        public IActionResult Create()
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["SpecialTagId"] = new SelectList(_db.SpecialTagNames.ToList(), "Id", "SpecialTagName");
            return View();
        }


        //Post Create Method
        [HttpPost]

        public async Task<IActionResult>Create(Books books, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                var searchBook = _db.Books.FirstOrDefault(c => c.Title == books.Title);
                if (searchBook != null)
                {
                    ViewBag.message = "This product already exists!";

                    ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
                    ViewData["SpecialTagId"] = new SelectList(_db.SpecialTagNames.ToList(), "Id", "SpecialTagName");
                    return View();
                }
                if(image!= null)
                {
                    var name = Path.Combine(_he.WebRootPath+"/images",Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    books.Image = "images/" + image.FileName;
                }
                _db.Books.Add(books);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(books);
        }

        //Get Edit Action Method
        
        public ActionResult Edit(int? id)
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["SpecialTagId"] = new SelectList(_db.SpecialTagNames.ToList(), "Id", "SpecialTagName");
            if(id==null)
            {
                return NotFound();
            }
            var book = _db.Books.Include(c => c.ProductTypes).Include(c => c.SpecialTagName)
                .FirstOrDefault(c => c.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }
        [HttpPost]
        //POST Edit Action Method
        public async Task<IActionResult> Edit(Books books, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    books.Image = "images/" + image.FileName;
                }
                _db.Books.Update(books);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(books);

        }

        //Get Details Action Method
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = _db.Books.Include(c => c.ProductTypes).Include(c => c.SpecialTagName)
                .FirstOrDefault(c => c.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        //Get Delete Action Method
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = _db.Books.Include(c => c.SpecialTagName).Include(c => c.ProductTypes).Where(c => c.Id == id).FirstOrDefault();
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        //Post Delete Action Method
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = _db.Books.FirstOrDefault(c => c.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            _db.Remove(book);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

BookStore/Areas/Admin/Controllers/ProductTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BookStore.Data;
using BookStore.Models;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductTypesController : Controller
    {
        private ApplicationDbContext _db;

        public ProductTypesController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //var data = _db.ProductTypes.ToList();
            return View(_db.ProductTypes.ToList());
        }

        //Create Get Action Method
        public ActionResult Create()
        {
            return View();
        }

        //Create Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Add(productTypes);
                await _db.SaveChangesAsync();
                TempData["save"] = "Category saved";
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }

        //Edit Get Action Method
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        //Edit Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.Update(productTypes);
                await _db.SaveChangesAsync();
                TempData["update"] = "Category Updated";
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }

        //Details Get Action Method
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        //Details Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Details(ProductTypes productTypes)
        {
            return RedirectToAction(nameof(Index));
            
        }

        //Delete Get Action Method
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        //Delete Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Delete(int? id, ProductTypes productTypes)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (id!=productTypes.Id)
            {
                return NotFound();
            }

            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(productType);
                await _db.SaveChangesAsync();
                TempData["remove"] = "Category deleted";
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }



    }
}

BookStore/Areas/Admin/Controllers/SpecialTagNamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpecialTagNamesController : Controller
    {
        private ApplicationDbContext _db;

        public SpecialTagNamesController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //var data = _db.ProductTypes.ToList();
            return View(_db.SpecialTagNames.ToList());
        }

        //Create Get Action Method
        public ActionResult Create()
        {
            return View();
        }

        //Create Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(SpecialTagNames specialTagNames)
        {
            if (ModelState.IsValid)
            {
                _db.SpecialTagNames.Add(specialTagNames);
                await _db.SaveChangesAsync();
                TempData["save"] = "Category saved";
                return RedirectToAction(nameof(Index));
            }
            return View(specialTagNames);
        }

        //Edit Get Action Method
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTagName = _db.SpecialTagNames.Find(id);
            if (specialTagName == null)
            {
                return NotFound();
            }
            return View(specialTagName);
        }

        //Edit Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(SpecialTagNames specialTagNames)
        {
            if (ModelState.IsValid)
            {
                _db.Update(specialTagNames);
                await _db.SaveChangesAsync();
                TempData["update"] = "Category Updated";
                return RedirectToAction(nameof(Index));
            }
            return View(specialTagNames);
        }

        //Details Get Action Method
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTagName = _db.SpecialTagNames.Find(id);
            if (specialTagName == null)
            {
                return NotFound();
            }
            return View(specialTagName);
        }

        //Details Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Details(SpecialTagNames specialTagNames)
        {
            return RedirectToAction(nameof(Index));

        }

        //Delete Get Action Method
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTagName = _db.SpecialTagNames.Find(id);
            if (specialTagName == null)
            {
                return NotFound();
            }
            return View(specialTagName);
        }

        //Delete Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Delete(int? id, SpecialTagNames specialTagNames)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (id != specialTagNames.Id)
            {
                return NotFound();
            }

            var specialTagName = _db.SpecialTagNames.Find(id);
            if (specialTagNames == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(specialTagName);
                await _db.SaveChangesAsync();
                TempData["remove"] = "Category deleted";
                return RedirectToAction(nameof(Index));
            }
            return View(specialTagNames);
        }



    }
}

BookStore/Views/Shared/_ButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width: 140px">
    <div class="btn-group">
        <a asp-action="Edit"  class="btn btn-primary" asp-route-id="@Model"><i class="far fa-edit"></i></a>
        <a asp-action="Details"  class="btn btn-success" asp-route-id="@Model"><i class="fas fa-info-circle"></i></a>
        <a asp-action="Delete"  class="btn btn-danger" asp-route-id="@Model"><i class="fas fa-trash-alt"></i></a>
    </div>
</td>

BookStore/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using BookStore.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{ 
    int count = 0;
    List<Books> books = HttpContextAccessor.HttpContext.Session.Get<List<Books>>("books");
    if (books == null)
    {
        books = new List<Books>();
    }
    count = books.Count();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookMarket</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </environment>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/alertify.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <style>

        .error {
            color: red;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <span> <img src="~/images/Logo.png" height="50" width="315" /> </span> 
                <ul class="nav navbar-nav">
                    <li><a asp-area="Admin" class="navbar-text" asp-controller="ProductTypes" asp-action="Index">Category</a></li>&nbsp;&nbsp;&nbsp;
                    <li><a asp-area="Admin" class="navbar-text" asp-controller="SpecialTagNames" asp-action="Index">Tag Name</a></li>&nbsp;&nbsp;&nbsp;
                    <li><a asp-area="Admin" class="navbar-text" asp-controller="Book" asp-action="Index">Book</a></li>&nbsp;&nbsp;&nbsp;
                    <li><a asp-area="" class="navbar-text" asp-controller="Home" asp-action="About">About</a></li>&nbsp;&nbsp;&nbsp;
                    <li><a asp-area="" class="navbar-text" asp-controller="Home" asp-action="Contact">Contact</a></li>&nbsp;&nbsp;&nbsp;
                    <li>
                        <a asp-area="Customer" class="navbar-text" asp-controller="Home" asp-action="Cart">
                            <i class="fa fa-shopping-cart"></i>
                            (@count)
                        </a>
                    </li>&nbsp;&nbsp;&nbsp;
                </ul>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;  @DateTime.Now.Year - BookMarket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <environment include="Development">
        @*<script src="https://code.jquery.com/jquery-3.3.1.js"></script>*@
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>*@
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>


    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>